' DEFS.INC
'
' Constant definitions required by directory routines
' Copyright (C) Robert J. Showalter, 1987.  CompuServe ID 72220,466.
'

      %FALSE        = 0
      %TRUE         = not %FALSE
      %MSDOS        = &h21              ' DOS function call interrupt
      %FLAGS        = 0                 ' register names
      %AX           = 1
      %BX           = 2
      %CX           = 3
      %DX           = 4
      %SI           = 5
      %DI           = 6
      %BP           = 7
      %DS           = 8
      %ES           = 9
