Declare Sub DisplayBallField_Gfx (nbrBalls, nbrStrikes)
Declare Sub DisplayRun_G (baseNbr, Xcoord)
Declare Sub HOLDSTATUS_G (H0%)
Declare Sub DisplayInning_G (currInning, teamLine)
Declare Sub LOADSCREEN ()
Declare Sub MAINSCREEN_G (nbrBalls, nbrStrikes, MO)
Declare Sub PrintOnGfx (Col%, Row%, Text$, tgtScrn&)
