Declare Sub DisplayBallField_Gfx (BC%, p, U%, D)
Declare Sub DisplayRun_G (I2, p, X)
Declare Sub HOLDSTATUS_G (H0%)
Declare Sub INNDISP_G (currInning, teamLine)
Declare Sub LOADSCREEN ()
Declare Sub MAINSCREEN_G (D, p, BC%, U%, MO)
Declare Sub PrintOnGfx (Col%, Row%, Text$, tgtScrn&)
