Carrigan
 5 
Chylak
 3 
DiMuro
 6 
Valentine
 5 
Drummond
 4 
Flaherty
 4 
Haller
 3 
Honochick
 3 
Hurley
 3 
Kinnamon
 4 
McKinley
 4 
Napp
 3 
Paparella
 5 
Rice
 5 
Runge
 5 
Salerno
 5 
W.Smith
 5 
Soar
 4 
Stevens
 4 
R.Stewart
 3 
Umont
 3 
Neudecker
 5 
Odom
 5 
Springstead
 5 

 5 

 5 

 5 

 5 

 5 

 5 

 5 

 5 

 5 

 5 

 5 

 5 

 5 

 5 

 5 

 5 

 5 

 5 

 5 

 5 

 5 

 5 

 5 

 5 

 5 

 5 
